language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3              # Same version as specified in build.gradle
    - android-28                      # SDK version
    - extra-android-m2repository      
    - extra-google-m2repository 
    - sys-img-armeabi-v7a-android-22  # Android Image
	
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+